### ISSUE TITLE
Dynamics Trials

### ISSUE THREAD

**Issue by zeeb33** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#113]
# Exercise: 01
## Step: 02

Description of issue
Unable to complete company set up as the extended trial is used up. 

Repro steps:
Users will receive an error when creating companies stating their "license does not grant the following permissions".
![image](https://user-images.githubusercontent.com/42649591/172206424-41dd6dff-aea5-4a01-9019-50a7451c1881.png)
![image](https://user-images.githubusercontent.com/42649591/172206644-6f1ef0d0-6179-470c-b56c-80c9793c91b3.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by hakimmartin** [comment]
Updated the steps in Lab 0 which addresses this issue.
