### ISSUE TITLE
MB-800 - module 5 - lab 5.1 errors in lab instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#114]
# Module:5
#### Step: 1a

Description of issue - the V9002 is not Cronus Cardoxy Sales - but it is Robert Townes
I have taken Robert Townes to proceed, but came across further issues as described below...

# Module:5
#### Step: 2d ii

Description of issue - when entering CHW1002 as the product, I get an error message to say "validation results - The tax posting setup does not exist. identification fields and values: VAT Bus. posting group =, VAT prod posting group =".

How do i fix this please?

**Comment by hakimmartin** [comment]
This issue may be related to a missed step in Lab 5, exercise 1.You need to make sure that the correct address is selected and include the correct country code value of 'DK'. Once the address is correct, the tax posting setup should validate.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by hakimmartin** [comment]
Was not able to reproduce

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue

**Comment by chaast** [comment]
can this be reopened please if MOC labs confirms this issue?
