### ISSUE TITLE
Missing Graphics in /Media dir

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#117]
# Module: 04 + 05

Description of issue

**Module 4 issue:**  In https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BMB-800%5D_M04_Lab01_Set_up_Inventory.md

- Exercise 2, 'Scenario' section there is a reference to a graphic that is not present in the /media dir:

218a200ca941d82415b500899e506920.png

**Module 5 issue:** In https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BMB-800%5D_M05_Lab01_Process_Purchase.md

- Exercise 2, Step 5 (the 2nd 'Step 5'...since the numbering also seems to be broken somewhat) is another example of a reference to a graphic that is not present in the media dir, plus appears to be some stray Dutch:

5.  Select the line for G/L entries and select **Show Related Entries**.

9b9348a77204aa5451411df60c20fbf0.png

>   Afbeelding met tafel Automatisch gegenereerde beschrijving

**Comment by hakimmartin** [comment]
Added the images
