### ISSUE TITLE
LAb 5.4 - process financial transactions -- errors throughout ex 2-5

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#118]
# Module: 5.4

**Please run through the whole of this lab -- excel files incorrect data, not uploading correctly into the system: missing records and data on existing records, resulting in the following erros:**
* Exercise 2 - errors on step 5 - post the general journal
* Exercise 3 - There is no rapidstart package provided as part of the lab, only excel / errors on step 2f
* Exercise 4: the name of the vendor does not exist, attempted to run with V9005, but unable to process payment journals due to errors. the records do not hold the required information.
* Exercise 5: step1 is ok, step 2  process pyament registrations - unable to carry out as the documents referenced in this step are not present in the lab environment

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by hakimmartin** [comment]
The correct Excel files were re-uploaded. These lab steps can now be executed. 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/71838770/195614748-1c446353-1d30-49df-b36a-8148bc11b8ca.png">

**Comment by chaast** [comment]
thank you - I will run through the exercise with these updated excel files
