### ISSUE TITLE
Lab numbering doesn't agree with lab document names in 2 docs

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#146]
## Lab/Demo: 05 & 06

Description of issue

The numbering of 2 (possibly 3) of the lab documents as seen in their names, vs. the numbering as seen in the title within the document appears to be out-of-order and can be confusing to students.

- Document: https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BMB-800%5D_M05_Lab03_Process_Cash_Mngmentt.md

It is listed as M05_Lab0**3** in its name, but its instructions title says it is 5.**2**:
![image](https://user-images.githubusercontent.com/49700217/194175702-486cbd7e-41fe-4303-bd69-4c2e678bfc89.png)

- Document: https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BMB-800%5D_M06_Lab01_Set_up_purchase_approval_workflow.md

It is listed as M0**6**_Lab0**1**, but its instructions title says it is 5.**3**:
![image](https://user-images.githubusercontent.com/49700217/194175913-0c0cd161-a3a0-4152-9917-e85894b217ba.png)

- Document: https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/blob/master/Instructions/Labs/LAB%5BMB-800%5D_M06_Lab01_Setting_up_purchase_approval.md

It is also listed as M06_Lab01, so depending on how the previous document is renumbered, this might need to change to...6.2, or...?
![image](https://user-images.githubusercontent.com/49700217/194176073-5465c2f3-ffed-45fa-aa16-15962beaeb09.png)

**Comment by hakimmartin** [comment]
Updated the lab numbering to match the correct ordering.
