### ISSUE TITLE
Practice Lab - Validate lab environment steps are out of date

### ISSUE THREAD

**Issue by ivor-mct** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#180]
# Module: 00
#### Step: 1 and 2

Instructions as provided in the lab are out of date. Current instructions when followed leave participants in a loop of new tabs when the Try for free link is clicked.

I would suggest that the URL be modified to the [Business Central Sign In page](https://businesscentral.dynamics.com) and have the participants click on Sign In with lab hosting provider credentials. This ensures that they can complete the process of sign up for the Business Central trial while avoiding the aforementioned loop.

**Comment by chaast** [comment]
I experienced the same - for me what fixed it was to click "yes, switch to my location" on the prompt that comes up on the screen.

**Comment by ivor-mct** [comment]
Unfortunately, I didn't have that option on my end.

**Comment by Nagakirthi** [comment]
Hi, Could you please share the screenshot

**Comment by Nagakirthi** [comment]
Hi, The latest link for the business central is updated in the Lab guides.
