### ISSUE TITLE
Lab 2.1 - Exercise 2 - complete the company setup wizard - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#181]
# Module: 2.1
#### Step: 0d

Description of issue
* There is no company called Contoso Ltd... I assume it is meant to say, select Contoso 'student name', as created in the previous task.

**Comment by Nagakirthi** [comment]
The Lab guide is updated accordingly.

**Comment by chaast** [comment]
that's great. thank you.

**Comment by dbuchnowska** [comment]
the mistake still exist - Lab 1., Ex 2

**Comment by a-ainamdar** [comment]
Hi
Thank you for raising this. I can also reproduce it. We are in the process of updating instructions.
