### ISSUE TITLE
Module 2, Exercise: create and export a configuration package

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#182]
# Module: 02
#### Step: b

Description of issue
Enter the information as provided by contoso... what information? there is nothing in the lab to show what information needs to be provided. Please make it clear - this step refers to the vendor import file.

Now i have located the file, i found out that my lab environment does not allow me to edit the excel file. Is this an error in the setup by the lab provider?

**Comment by Nagakirthi** [comment]
The excel is data is now updated in the Lab guide accordingly.

**Comment by chaast** [comment]
that's great. thank you.
