### ISSUE TITLE
Lab 3.5 - Purchases & Payables setup - exercise 3 - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#185]
# Lab: 3.5
#### Step: all the way through

Description of issue
* instructions say to select a gen. bus. posting group that does not exist. Please clarify whether students can pick the "international" gen. bus. posting group instead of the missing ones - or do the missing ones have to be created too?

**Comment by Nagakirthi** [comment]
Kindly share the screenshot if possible.

**Comment by chaast** [comment]
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/63a9afb5-bcaa-4bde-8e18-98f1a597289a)

here is a screenshot of the only two Gen. bus. posting groups that the lab has instructed to create.

**Comment by Nagakirthi** [comment]
Please share the step that you are executing and you get this screenshot

**Comment by chaast** [comment]
why? what difference does that make? the posting group described in the lab does not exist!

**Comment by chaast** [comment]
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/680f91e3-dde8-4951-b294-1ac1c55cd6c8)

**Comment by Nagakirthi** [comment]
Hi, updated the labs guides accordingly to create a new one if it is not present.

**Comment by chaast** [comment]
that's great. thank you.
