### ISSUE TITLE
Lab 3.6 Sales & Receivables setup - exercise 3 - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#186]
# Lab: 3.6
#### Step: 03b - enter the information as provided by contoso

Description of issue
* what information? there is no image or excel spreadsheet or image provided! 

this is causing issues later on too, as my customer names now do not match with the names given in the rest of the labs.

**Comment by Nagakirthi** [comment]
Hi,

The lab instructions is updated with the data.
