### ISSUE TITLE
Lab 4.1 - configure the inventory setup - exercise 2 - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#187]
# Lab 4.1
#### Step: j - In the General Posting Setup page, for each combination where the Gen. Prod. Posting Group field contains the value COMPUTERHW, make sure the following fields are filled in:

Description of issue
There is no such combination. are the delegates expected to create the combinations?

Perhaps it will be clearer for delegates to say in step 4di - create the gen. prod. posting group for computerhw.. then click set up to create 3 combinations - one with gen. bus. posting group blank, one with domestic and one for international, and then fill in the required fields..

**Comment by Nagakirthi** [comment]
Hi,

Will the steps for that accordingly.

**Comment by chaast** [comment]
Sorry - what do you mean? can you please clarify in better written english?

**Comment by chaast** [comment]
thanks you for much for your help.

**Comment by Nagakirthi** [comment]
Hi, 
The labs guides are updated accordingly with proper instructions now
