### ISSUE TITLE
Lab 4.3 - exercise 1 -  task 3 set up and assign a sales person - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#188]
# Lab : 4.3
#### Step: gii

Description of issue
If you try to type in AH in the dimension value code the system errors. the only way to get past this is to leave that field blank.

Also -- i don't have the customers listed in steps j / m / o -- mine are called Jesse Homer / first up consultants / fabrikam...

**Comment by Nagakirthi** [comment]
Hi, Please share the screenshot

**Comment by Nagakirthi** [comment]
If you try to type in AH in the dimension value code the system errors. the only way to get past this is to leave that field blank. - Will add the steps accordingly.

Also -- i don't have the customers listed in steps j / m / o -- mine are called Jesse Homer / first up consultants / fabrikam... - Try to perform the steps in the default company that was there- Cronus USA,Inc

**Comment by chaast** [comment]
When you say "Will add the steps accordingly?" -- does this mean you will update the lab?


Why should i go suddenly to cronus USA? the lab does not instruct this... please update the lab accordingly so that the correct customers are showing!

**Comment by chaast** [comment]
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/99a6eaa0-2095-4695-883c-9bfc99cf252e)

Here is the screenshot with the error when i try to select AH in step gii ...

**Comment by chaast** [comment]
thank you for updating the lab and for your understanding of my frustration with these course labs! 

The full instructions need  checking and updating please -- there are just way too many errors impacting my course delivery.

**Comment by Nagakirthi** [comment]
Hi, The lab guides is updated with proper instructions and updated
