### ISSUE TITLE
Lab 5.1- process purchase - missing instructions in previous labs causing errors

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#189]
# Lab: 5.1
#### Step: l

Description of issue
Gen Business posting groups and Gen. product posting groups have not been setup correctly. in the previous exercises - please include instructions to fill in the purchase account and sales account fields too.

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/eb0ac890-00f3-4f65-9d9a-cfabf04c0a9c)

#### Step: d

* as per above -- purchase credit memo account should also be filled in!

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/db09471c-91f8-4f19-aab7-a9ea3d48e420)

**Comment by Nagakirthi** [comment]
Hi, Will update the lab guides

**Comment by chaast** [comment]
that's great. thank you.

**Comment by J0eGos** [comment]
Are you able to tell me what values you used for the Sales account and purchase accounts? (if you completed this task anyway)

**Comment by hakimmartin** [comment]
Lab steps updated
