### ISSUE TITLE
Lab 5.2 - description of labs not inline with what is happening on screen

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#190]
# Lab: 5.2
#### Step: i and r and aa

Description of issue
* the jobs are not being placed in job queue -- there is no option to click ok

# Lab: 5.2
#### Step: h

the system has not posted the invoice - is this correct?
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/2fadd41a-ffb9-4d9d-b967-686479d9c7ce)

**Comment by Nagakirthi** [comment]
Under Sell - to - customers, you must select Generic EU webshop to combine the shipments and for invoice to be created. We have updated the lab guides

**Comment by chaast** [comment]
that's great. thank you.
