### ISSUE TITLE
Lab 5.3 - exercise 1 - process cash management - incorrect instructions on post the general journal

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#191]
# Lab: 5.3
#### Step: b

Description of issue

* I have clicked on the general ledger setup page -- but cannot see what is meant by select the first line...  

Does it meant to say "go to General Journals"? that would make more sense...

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/4f0ace8d-3521-46a0-8993-1a104755e898)

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/ffb8e46f-f757-45eb-9e0f-a5fd30db32a9)

**Comment by Nagakirthi** [comment]
Hi, Executed the lab again and updated the steps of the labs
