### ISSUE TITLE
Lab 5.3 - exercise 2 - there is no rapidstart package for this lab - only an excel document

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#192]
# Module: 5.3
#### Step: b

Description of issue
* Please amend instructions to say import from excel, rather than import package.  or please make a rapidstart package available. 
* 
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/bbb87320-f0ef-4bba-824a-64f0e50b4072)

**Comment by chaast** [comment]
also in this lab: 

error message when trying to post the CUST and VEND journal batch. - please test this lab and modify instructions:
1) for CUST, people need to complete Balance Account Number for all records, -- it mentions to ent 101100 in account no field - but this should say Balance account number field ( step 2diii)

2) for VEND posting - balance account no also need to be filled in, not just the posting date field of step 2k.

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/407cc026-044b-4843-9354-cde509528a72)

**Comment by Nagakirthi** [comment]
Hi, Executed the lab and updated the steps in Lab guide

**Comment by chaast** [comment]
that's great. thank you.
