### ISSUE TITLE
Lab 5,.3 - exercise 3 -- there is no vendor called first up consultants

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#193]
# Module: 5.3
#### Step: 1

Description of issue
* Please update the lab with a vendor that is actually on the list: V9005 Fabrikam maybe?

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/78ed2530-b55e-4b5c-9b57-48cb3304f9a0)

**Comment by chaast** [comment]
also on this lab - there is an error when trying to bank > export... but it is not clear how to fix this.

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/a677c1c0-a723-4a2c-9ba5-fec1029146f4)

**Comment by Nagakirthi** [comment]
Hi,

On the Business Central Home page, Click on search icon and Enter Bank Account and click on related link. Select the EUROP account and enter a value for Credit transfer msg field.

**Comment by chaast** [comment]
that's great. thank you.
