### ISSUE TITLE
Lab 5.3 - Exercise 4 process customer registration - record does not exist

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#194]
# Module: 5.3
#### Step: c

Description of issue
* the record referred to in the lab does not exist - i assume we take order 101005 - for Francematic?

 
![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/47ea3137-efd2-4943-854a-f375b5726931)

**Comment by Nagakirthi** [comment]
Hi, Updated the lab guide accordingly for Francematic

**Comment by chaast** [comment]
that's great. thank you.
