### ISSUE TITLE
Lab 6.1 -- unable to carry out -- there are no other users in the system 

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#195]
# Module: 06
#### Step: 01

Description of issue

even though i have 19 students on my course.. i cannot see them in the list to select "approval user set up". therefore i am unable to carry out the labs. my students will face the same issue.

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/89986870/863f82ad-beee-44ec-8b89-7bdd641e087f)

To fix: please include steps on how to create users and assign licences. thank you.

**Comment by Nagakirthi** [comment]
Hi, the steps for adding the users and updating those added users are added to the lab and is available. You can add users from admin center.

https://admin.microsoft.com/.
