### ISSUE TITLE
Vendors missing in Lab 3.5 Microsoft Dynamics 365 Business Central Functional Consultant

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#196]
# Module: 3.5
### Step: 13

Description of issue
Step 13 of Exercise 3 in Lab 3.5 instructs you to apply the vendor template on Vendors 9001, 9002, 9003, 9005, 9006, and 9007, but these vendors are not listed in Dynamics 365 Business Central. Only Vendors 10000, 20000, 30000, and 40000 are available.

![image](https://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant/assets/94069201/44f5724b-cd3f-4347-984a-55bfc584ad85)

**Comment by dipali1709** [comment]
I am facing the same issue. I have one solution for that , we  can create the new vendor template on Vendors 9001, 9002, 9003, 9005, 9006, and 9007. I will try this option and update here.

**Comment by dipali1709** [comment]
If you are unable to find the Vendors you can create the vendors. I did that and my issue got resolved.

**Comment by hakimmartin** [comment]
Still working on this issue, looking to have it resolved by the end of this week. You can create a new vendor template but I am looking into why it doesn't already show.

**Comment by Nagakirthi** [comment]
Hi,

We have updated the lab guide with steps regarding adding new vendors and proceeding further with the later steps.

**Comment by hakimmartin** [comment]
Lab steps have been updated.

**Comment by dipali1709** [comment]
Thankyou for all .
