### ISSUE TITLE
Exercise 6: Set Up General Journals. Repeated lab steps for Task 1

### ISSUE THREAD

**Issue by Ellywati** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#202]
# Module: 2
#### Step: 01

Description of issue

This lab has been repeated twice, the scenario are exactly the same, for Task 1 and Task 2. 
Please update accordingly. 

Thank you

**Comment by KashifKhaan** [comment]
Yes! The tasks are repeated.

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. I am raising PR to remove this repeated task.
