### ISSUE TITLE
Exercise 9 : Process Cash Management, missing rapidstart package

### ISSUE THREAD

**Issue by Ellywati** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#203]
# Module: 00
#### Step: 01

Description of issue
The rapidstart package does not exist in the lab download folder. 

Repro steps:

1. Import and apply a predefined package containing historical data (customer and vendor open entries).

- Select the search for page icon in the top-right corner of the page, enter Configuration Packages, and then choose the related link.
- On the Configuration Packages page, select the OPENING package and then select Import Package.
- Click on Click here to browse.
- **_Select the rapidstart package._**
- In the Config. Package Card page, select Package and then Apply Package.
- Click Yes.
- Click OK.

**Comment by HashirSajjad** [comment]
Any update on this? I am facing similar issue also.

**Comment by hakimmartin** [comment]
Currently working on retesting the exercises here. We'll be able to provide feedback soon.

**Comment by a-ainamdar** [comment]
Thank you for your feedback. We are reviewing this issue. 
We will keep you posted.

**Comment by a-ainamdar** [comment]
Hi Ellywati,

rapidstart package file has been uploaded for the labs. kindly check again and let us know in case of any issues.

Thank you

**Comment by hakimmartin** [comment]
Verified this issue is now resolved.
