### ISSUE TITLE
Lab 5 task 1 Number of account

### ISSUE THREAD

**Issue by dbuchnowska** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#205]
# Module: 00
#### Step: 
2.  Assign default dimensions to multiple G/L Accounts
    1.  In the **Chart of Accounts** page, select general ledger accounts 60110 until 61170.
Description of issue
There is no account no 61170

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We are currently updating this lab and will let you know once updated.
