### ISSUE TITLE
Checking on the Pull requests. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#21]
Hi, 

Checking on these Pull requests from LOD. 
Any timeline on these? 
Thanks.

**Comment by hope77777** [comment]
Checking on these pull requests again. 
Can someone take a look?
Thanks.

**Comment by hakimmartin** [comment]
Hi @hope77777 ,

I am looking into this in hopes to getting some resolutions this week.

Thanks
