### ISSUE TITLE
Poor Quality

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#24]
# Module: 00
#### Step: 00

Description of issue
this is supposed to be a guided lab for students to learn. the quality of the lab is very poor, just a set of steps without minor explanation of any of them and without any comment on why we do things this way.

I am an MCT instructor and I have done many labs recently PL-900 and DA 100 and they were very good explained. It is really frustrating to find this poor material as an official lab from Microsoft on such an important product like business central
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021
