### ISSUE TITLE
Account 20175 doesnt exist

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#25]
# Module: 00
#### Step: 00

Description of issue
Module 3
exercise 3
step 1
there is a reference to Account 20175 that doesn't exist, or has not been created in previous modules
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue
