### ISSUE TITLE
account 10475 doesnt exist

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#26]
# Module: 3
#### Step: 6

Description of issue
account 10475 doesnt exist and it has not been created in previous exercises
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue
