### ISSUE TITLE
wrong steps

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#27]
# Module: 3
#### Step: 9-19

Description of issue
every time I go to customers page and I create a new customer I have to chose from a template. this step is not mentioned in the lab, I also have no option to skip this step. please check this lab carefully it if full of mistakes and very bad quality
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021
