### ISSUE TITLE
previous customer created  is ignored in the exercise

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#29]
# Module: 3
#### Step: 27

Description of issue
we previously create a customer manually (module 3 exercise 1 and step 1) with numeric series  CWEB and name: Generic EU web shop .

when we export the excel file this customer is included.

from the screenshot provided in the exercise the customer list has numeric series of C0001/2/3..
the screenshot also ignores the previously created customer and there is no mention in the guided steps whether this is intentional or should we keep the previously created one or delete it.

a lack of description and a fully random preparation

Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021
