### ISSUE TITLE
sales person list is not provided

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#31]
# Module: 4
#### Step: 2

Description of issue
the lab is referring to sales person : Annette Hill.

this list of sales people have not been created before. I still don't understand how would you release an official lab with this poor quality, it has never been revised apparently
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021
