### ISSUE TITLE
there is no invoicing tab in ITEM card 

### ISSUE THREAD

**Issue by MTawfik86** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#32]
# Module: 4
#### Step: 600

Description of issue
the guide is referring to invoicing tab in ITEM card, there is no such tab in ITEM card, the item.desc.group is found in the Price and sales tab
Repro steps:

1.
1.
1.

**Comment by hakimmartin** [comment]
Labs have been refreshed in January 2021
