### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by zbskillable** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#63]
Description of issue

There are several broken image links in this lab. They can be found in modules 3.2, 3.4, 5.2, 5.4, and 5.5. The text associated with these images is also showing up in Dutch. 

![3 2](https://user-images.githubusercontent.com/42649591/156365054-59b977d3-5ae0-44b5-a3c3-07268c6f0b65.png)
![3 4 1](https://user-images.githubusercontent.com/42649591/156365059-23b88604-ccbc-4ecc-ae5d-74c863aa8cb0.png)
![3 4](https://user-images.githubusercontent.com/42649591/156365060-e97fc49c-26d7-4126-9817-0840f7ec8229.png)
![5 2](https://user-images.githubusercontent.com/42649591/156365063-4bd9148e-a294-4294-bb8b-d97b699bb988.png)
![5 4](https://user-images.githubusercontent.com/42649591/156365065-af8e844d-f59e-419c-b91a-79a17b4fcea2.png)
![5 5](https://user-images.githubusercontent.com/42649591/156365067-97df5c0a-277f-411d-b807-c381802a56ac.png)
.

**Comment by hakimmartin** [comment]
Fixed all image issues
