### ISSUE TITLE
Allow Payment Export box not present.

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#9]
# Module: 03
#### Step: 08 iii

Description of issue
The step says to check the "Allow Payment Export" box. The box does not exist on the Journal Batches page.
Repro steps:

1. Go to Journal Templates page
1. Makes sure EUROP is selected
1. Click more options, then Related, then Template, then batches.
1. When you try to create a new item there is no "Allow Payment Export" box to select.

**Comment by hakimmartin** [comment]
Hi @LodsCory - On this issue, the "Allow Payment Export" box is on the table, you just need to hit the Tab key while you are in the table until you see the checkbox. Attaching an image for reference. Please let me know if you have any further issues with this.

<img width="641" alt="Allow Payments Export" src="https://user-images.githubusercontent.com/71838770/112911771-1a0d4880-90c4-11eb-8f0e-e6c66774184a.PNG">

**Comment by LodsCory** [comment]
Thank you for clarifying!
